export const Flag = {
  WORLD: { code: '🌎', name: 'World' },
  USA: { code: '🇺🇸', name: 'United States' },
  CANADA: { code: '🇨🇦', name: 'Canada' },
  BRAZIL: { code: '🇧🇷', name: 'Brazil' },
  ARGENTINA: { code: '🇦🇷', name: 'Argentina' },
  UK: { code: '🇬🇧', name: 'United Kingdom' },
  FRANCE: { code: '🇫🇷', name: 'France' },
  GERMANY: { code: '🇩🇪', name: 'Germany' },
  DENMARK: { code: '🇩🇰', name: 'Denmark' },
  SWEDEN: { code: '🇸🇪', name: 'Sweden' },
  NORWAY: { code: '🇳🇴', name: 'Norway' },
  FINLAND: { code: '🇫🇮', name: 'Finland' },
  POLAND: { code: '🇵🇱', name: 'Poland' },
  BELGIUM: { code: '🇧🇪', name: 'Belgium' },
  NETHERLANDS: { code: '🇳🇱', name: 'Netherlands' },
  SPAIN: { code: '🇪🇸', name: 'Spain' },
  PORTUGAL: { code: '🇵🇹', name: 'Portugal' },
  ITALY: { code: '🇮🇹', name: 'Italy' },
  SWITZERLAND: { code: '🇨🇭', name: 'Switzerland' },
  AUSTRIA: { code: '🇦🇹', name: 'Austria' },
  RUSSIA: { code: '🇷🇺', name: 'Russia' },
  UKRAINE: { code: '🇺🇦', name: 'Ukraine' },
  KAZAKHSTAN: { code: '🇰🇿', name: 'Kazakhstan' },
  LITHUANIA: { code: '🇱🇹', name: 'Lithuania' },
  LATVIA: { code: '🇱🇻', name: 'Latvia' },
  ESTONIA: { code: '🇪🇪', name: 'Estonia' },
  CZECHIA: { code: '🇨🇿', name: 'Czechia' },
  SLOVAKIA: { code: '🇸🇰', name: 'Slovakia' },
  HUNGARY: { code: '🇭🇺', name: 'Hungary' },
  TURKEY: { code: '🇹🇷', name: 'Turkey' },
  BULGARIA: { code: '🇧🇬', name: 'Bulgaria' },
  ROMANIA: { code: '🇷🇴', name: 'Romania' },
  SERBIA: { code: '🇷🇸', name: 'Serbia' },
  CROATIA: { code: '🇭🇷', name: 'Croatia' },
  GREECE: { code: '🇬🇷', name: 'Greece' },
  MONTENEGRO: { code: '🇲🇪', name: 'Montenegro' },
  NORTH_MACEDONIA: { code: '🇲🇰', name: 'North Macedonia' },
  BOSNIA: { code: '🇧🇦', name: 'Bosnia & Herzegovina' },
  ALBANIA: { code: '🇦🇱', name: 'Albania' },
  MOLDOVA: { code: '🇲🇩', name: 'Moldova' },
  CHINA: { code: '🇨🇳', name: 'China' },
  MONGOLIA: { code: '🇲🇳', name: 'Mongolia' },
  INDIA: { code: '🇮🇳', name: 'India' },
  SOUTH_KOREA: { code: '🇰🇷', name: 'South Korea' },
  JAPAN: { code: '🇯🇵', name: 'Japan' },
  AUSTRALIA: { code: '🇦🇺', name: 'Australia' },
  NEW_ZEALAND: { code: '🇳🇿', name: 'New Zealand' },
};
